# https://github.com/zmkfirmware/unified-zmk-config-template/blob/main/config/west.yml
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    # https://github.com/zmkfirmware/zmk/pull/2027
    # https://github.com/petejohanson/zmk/tree/feat/pointers-move-scroll
    - name: zmk
      remote: petejohanson
      revision: feat/pointers-move-scroll
      import: app/west.yml
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: main
    #   import: app/west.yml
  self:
    path: config
