#!/usr/bin/env bash

SIDE="$1"
west build \
	--pristine \
	--source zmk/app \
	--board nice_nano_v2 \
	-- \
	-DSHIELD="microdox_${SIDE}" \
	-DZMK_CONFIG=/root/config

mv build/zephyr/zmk.uf2 /root/dist/microdox_${SIDE}.uf2
ls -la /root/dist/microdox_${SIDE}.uf2
